services:
  - type: web
    name: miniurlshortener-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: miniurlshortener-db
          property: connectionString

databases:
  - name: miniurlshortener-db
    plan: free
    databaseName: miniurlshortener
    user: miniurl_user
