services:
  - type: web
    name: miniurlshortener-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: miniurlshortener-db
          property: connectionString
      - key: BASE_URL
        value: https://miniurlshortner-server.onrender.com

databases:
  - name: miniurlshortener-db
    plan: free
    databaseName: miniurlshortener
    user: miniurl_user
